### ISSUE TITLE
ESM import logs empty (and compressed) module objects, require returns compressed package object

### ISSUE THREAD

**Issue by somq** [coreybutler/iam#10]
## ESM

code
```js
import IAM from '@butlerlogic/node-iam'
console.log('IAM: ', IAM);
```
logs
```log
IAM:  re {}
```

## CommonJS / npm package

code
```js
const IAM = require('@butlerlogic/node-iam-legacy')
console.log('IAM: ', IAM);
```
log
```log
IAM:  {
  ze: [Function: f],
  Le: [Function: M],
  Ne: [Function: L],
  Ce: [Function: r],
  De: [Function: o],
  ee: [Function: I],
  default: re {}
}
```

## CommonJS / repo clone

code
```js
import IAM from '../src/main.js'
console.log('IAM: ', IAM);
```
log
```log
IAM:  Manager {}
user:  User {}
user.groups():  [ Group {} ]
user.roles:  [ Role {}, Role {} ]
```

## node version

```sh
node --version
v13.3.0
```

Is there something I'm doing wrong?

**Comment by coreybutler** [comment]
@somq - So sorry, this slipped past me. It looks like something got screwed up in the build process, because those are all minified property names. I will post here when I've fixed the release.

**Comment by coreybutler** [comment]
Apologies for this falling off the radar... _again_. Some changes were made (documented in the README) to the project structure/distribution and things are now working. It might be easier to get started by playing around with the [live example on Codepen](https://codepen.io/coreybutler/pen/mdEyQxX).
