### ISSUE TITLE
Persistence ?

### ISSUE THREAD

**Issue by kronos-999** [coreybutler/iam#14]
Are there any plans for persistence in Postgres or any other system? Would be the only way to use this in production.

**Comment by coreybutler** [comment]
There aren't plans specifically for persistence in Postgres. Most production systems maintain their system resources/roles/groups/etc using their own schema. These can be mapped to IAM. This can be used for non-relational systems as well, such as mapping LDAP or Active Directory groups/orgs/users to IAM. 

To make this simpler, IAM supports [loading a JSON configuration](https://github.com/coreybutler/iam/blob/master/src/lib/registry.js#L622). The configuration is accessible using the `IAM.configuration` property. You can see a working example of this at: https://github.com/coreybutler/iam/blob/6e3fed358e2d976e06b24ce770a862f0e805fb23/examples/ARCHIVE-%40butlerlogic-iam/ui/main.js#L142

The goal of this project is to remain database agnostic. However; if anyone decides to create a database-specific add-on/extension, I'd be happy to link to it in the README.
