### ISSUE TITLE
jsdelivr serves unminified source

### ISSUE THREAD

**Issue by gbdrummer** [coreybutler/iam#7]
There is a minification error in https://cdn.jsdelivr.net/npm/@butlerlogic/iam@latest/src/main.min.js

Here are the first few lines of the file:
```js
/**
 * Failed to minify the file using Terser v3.14.1. Serving the original version.
 * Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
 */
```

**Comment by coreybutler** [comment]
Resolved in d1d7de7c7e2f38a1dd7b9289d1662461a370e757.

The URL is a little different now: https://cdn.jsdelivr.net/npm/@butlerlogic/browser-iam@latest. 
It is also available at https://cdn.pika.dev/@butlerlogic/browser-iam@%5E1.0.1.

Note the URL's above are for the **browser** version. The README has been updated with all of the different [installation options](https://github.com/coreybutler/iam#installation).
